---
- name: provision development environment
  hosts: all
  roles:
    - base
  tasks:
    - name: set hostname
      become: yes
      become_user: root
      hostname:
        name: anvil.local
    - name: generate SSH key
      command: "ssh-keygen -t rsa -b 4096 -C '{{ user.email }}' -N '' -f {{ ansible_env.HOME }}/.ssh/id_rsa"
      ignore_errors: yes
      args:
        creates:
          - "{{ ansible_env.HOME }}/.ssh/id_rsa"
          - "{{ ansible_env.HOME }}/.ssh/id_rsa.pub"
    - become: yes
      become_user: root
      block:
        - name: disable static motd
          copy:
            content: ''
            dest: /etc/motd
          tags:
            - suppress-default-motd
        - name: install motd
          template:
            src: 20-logo.j2
            dest: /etc/update-motd.d/20-logo
            mode: '0755'
            backup: yes
    # TODO: install git hooks to PieCentral
