# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: run_mode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erun_mode.proto\"\x1e\n\x07RunMode\x12\x13\n\x04mode\x18\x01 \x01(\x0e\x32\x05.Mode*1\n\x04Mode\x12\x08\n\x04IDLE\x10\x00\x12\x08\n\x04\x41UTO\x10\x01\x12\n\n\x06TELEOP\x10\x02\x12\t\n\x05\x45STOP\x10\x03\x42\x02H\x03\x62\x06proto3')

_MODE = DESCRIPTOR.enum_types_by_name['Mode']
Mode = enum_type_wrapper.EnumTypeWrapper(_MODE)
IDLE = 0
AUTO = 1
TELEOP = 2
ESTOP = 3


_RUNMODE = DESCRIPTOR.message_types_by_name['RunMode']
RunMode = _reflection.GeneratedProtocolMessageType('RunMode', (_message.Message,), {
  'DESCRIPTOR' : _RUNMODE,
  '__module__' : 'run_mode_pb2'
  # @@protoc_insertion_point(class_scope:RunMode)
  })
_sym_db.RegisterMessage(RunMode)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _MODE._serialized_start=50
  _MODE._serialized_end=99
  _RUNMODE._serialized_start=18
  _RUNMODE._serialized_end=48
# @@protoc_insertion_point(module_scope)
