# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: runtime_status.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import run_mode_pb2 as run__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14runtime_status.proto\x1a\x0erun_mode.proto\"v\n\rRuntimeStatus\x12\x16\n\x0eshep_connected\x18\x01 \x01(\x08\x12\x16\n\x0e\x64\x61wn_connected\x18\x02 \x01(\x08\x12\x13\n\x04mode\x18\x03 \x01(\x0e\x32\x05.Mode\x12\x0f\n\x07\x62\x61ttery\x18\x04 \x01(\x02\x12\x0f\n\x07version\x18\x05 \x01(\tB\x02H\x03\x62\x06proto3')



_RUNTIMESTATUS = DESCRIPTOR.message_types_by_name['RuntimeStatus']
RuntimeStatus = _reflection.GeneratedProtocolMessageType('RuntimeStatus', (_message.Message,), {
  'DESCRIPTOR' : _RUNTIMESTATUS,
  '__module__' : 'runtime_status_pb2'
  # @@protoc_insertion_point(class_scope:RuntimeStatus)
  })
_sym_db.RegisterMessage(RuntimeStatus)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _RUNTIMESTATUS._serialized_start=40
  _RUNTIMESTATUS._serialized_end=158
# @@protoc_insertion_point(module_scope)
