# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_pos.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstart_pos.proto\"\x1d\n\x08StartPos\x12\x11\n\x03pos\x18\x01 \x01(\x0e\x32\x04.Pos*\x1a\n\x03Pos\x12\x08\n\x04LEFT\x10\x00\x12\t\n\x05RIGHT\x10\x01\x42\x02H\x03\x62\x06proto3')

_POS = DESCRIPTOR.enum_types_by_name['Pos']
Pos = enum_type_wrapper.EnumTypeWrapper(_POS)
LEFT = 0
RIGHT = 1


_STARTPOS = DESCRIPTOR.message_types_by_name['StartPos']
StartPos = _reflection.GeneratedProtocolMessageType('StartPos', (_message.Message,), {
  'DESCRIPTOR' : _STARTPOS,
  '__module__' : 'start_pos_pb2'
  # @@protoc_insertion_point(class_scope:StartPos)
  })
_sym_db.RegisterMessage(StartPos)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _POS._serialized_start=50
  _POS._serialized_end=76
  _STARTPOS._serialized_start=19
  _STARTPOS._serialized_end=48
# @@protoc_insertion_point(module_scope)
