# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: device.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65vice.proto\"^\n\x05Param\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x04\x66val\x18\x02 \x01(\x02H\x00\x12\x0e\n\x04ival\x18\x03 \x01(\x05H\x00\x12\x0e\n\x04\x62val\x18\x04 \x01(\x08H\x00\x12\x10\n\x08readonly\x18\x05 \x01(\x08\x42\x05\n\x03val\"I\n\x06\x44\x65vice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03uid\x18\x02 \x01(\x04\x12\x0c\n\x04type\x18\x03 \x01(\r\x12\x16\n\x06params\x18\x04 \x03(\x0b\x32\x06.Param\"#\n\x07\x44\x65vData\x12\x18\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x07.DeviceB\x02H\x03\x62\x06proto3')



_PARAM = DESCRIPTOR.message_types_by_name['Param']
_DEVICE = DESCRIPTOR.message_types_by_name['Device']
_DEVDATA = DESCRIPTOR.message_types_by_name['DevData']
Param = _reflection.GeneratedProtocolMessageType('Param', (_message.Message,), {
  'DESCRIPTOR' : _PARAM,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:Param)
  })
_sym_db.RegisterMessage(Param)

Device = _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
  'DESCRIPTOR' : _DEVICE,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:Device)
  })
_sym_db.RegisterMessage(Device)

DevData = _reflection.GeneratedProtocolMessageType('DevData', (_message.Message,), {
  'DESCRIPTOR' : _DEVDATA,
  '__module__' : 'device_pb2'
  # @@protoc_insertion_point(class_scope:DevData)
  })
_sym_db.RegisterMessage(DevData)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _PARAM._serialized_start=16
  _PARAM._serialized_end=110
  _DEVICE._serialized_start=112
  _DEVICE._serialized_end=185
  _DEVDATA._serialized_start=187
  _DEVDATA._serialized_end=222
# @@protoc_insertion_point(module_scope)
