# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timestamp.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftimestamp.proto\"?\n\nTimeStamps\x12\x16\n\x0e\x64\x61wn_timestamp\x18\x01 \x01(\x06\x12\x19\n\x11runtime_timestamp\x18\x02 \x01(\x06\x42\x02H\x03\x62\x06proto3')



_TIMESTAMPS = DESCRIPTOR.message_types_by_name['TimeStamps']
TimeStamps = _reflection.GeneratedProtocolMessageType('TimeStamps', (_message.Message,), {
  'DESCRIPTOR' : _TIMESTAMPS,
  '__module__' : 'timestamp_pb2'
  # @@protoc_insertion_point(class_scope:TimeStamps)
  })
_sym_db.RegisterMessage(TimeStamps)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _TIMESTAMPS._serialized_start=19
  _TIMESTAMPS._serialized_end=82
# @@protoc_insertion_point(module_scope)
